import { getSession, signOut, useSession } from 'next-auth/react';
import Head from 'next/head'
import Link from 'next/link'


export default function Home(props) {
  
  const {data:session} = useSession();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        session ? <User session={session} /> : <Guest />
      }
      
    </>
  )
}


const Guest = ()=> {
  
  return(
    <main className='container mx-auto text-center py-20'>
        <h3 className='text-4xl font-bold'>Gest Home Page</h3>
        <div className='flex justify-center'>
          <Link href={'/login'} className='mt-5 rounded-sm px-10 py-1 bg-gradient-to-r from-blue-500 to-indigo-500 text-gray-50' >Sign In</Link>  
        </div>  
    </main>
  )
}
const User = ({session})=> {

  const handleSignOut =  ()=>{
    signOut();
  }

  return(
    <main className='container mx-auto text-center py-20'>
        <h3 className='text-4xl font-bold'>Authorized User Page</h3>
        <div className='details'>
          <h5>{session.user.name}</h5>
          <h5>{session.user.email}</h5>
        </div>
        <div className='flex justify-center'>
          <button onClick={handleSignOut} className='mt-5 rounded-sm px-10 py-1 bg-gradient-to-r from-blue-500 to-indigo-500 text-gray-50' >Logout</button>  
        </div>  
        <div className='flex justify-center'>
          <Link href={'/profile'} className='mt-5 rounded-sm px-10 py-1 bg-gradient-to-r from-blue-500 to-indigo-500 text-gray-50' >Go to Profile</Link>  
        </div>  
    </main>
  )
}


export const getServerSideProps = async ({req})=>{
  const session = await getSession({req})
  if(!session){
    return{
      redirect:{
        destination:'/login',
      }
    }
  }
  
  return{
    props:{
      session
    }
  }
}